# Generated by Django 5.1.3 on 2024-11-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previsoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPlantada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('cultura', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ValorProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=100)),
                ('cultura', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Cultivo',
        ),
    ]
